info:
  contact: {}
paths:
  /v1/scan-results:
    get:
      consumes:
      - application/json
      description: Get Scan Result List with Offset & Payload
      produces:
      - application/json
      summary: Get Scan Result List
      tags:
      - Scan Results
    patch:
      consumes:
      - application/json
      description: Update Scan Result
      parameters:
      - description: Scan Result ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: Update Scan Result
      tags:
      - Scan Results
    post:
      consumes:
      - application/json
      description: Create Scan Result With ScanResult Payload
      produces:
      - application/json
      summary: Create Scan Result
      tags:
      - Scan Results
  /v1/scan-results/:id:
    delete:
      consumes:
      - application/json
      description: Delete Scan Result
      parameters:
      - description: Scan Result ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: Delete Scan Result
      tags:
      - Scan Results
    get:
      consumes:
      - application/json
      description: Get Scan Result Detail By ID
      parameters:
      - description: Scan Result ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: Get Scan Result Detail
      tags:
      - Scan Results
swagger: "2.0"
