version: "3.9"
services:
  db:
    image: mongodb
  dashboard:
    image: duybkit13/guardrails-dashboard
    ports:
      - "3001:3000"
  api:
    image: duybkit13/guardrails-api
    ports:
      - "3000:3000"
    depends_on:
      - "db"
